[package]
name = "doxidize"
version = "0.1.0"
authors = ["steveklabnik <steve@steveklabnik.com>"]
license = "MIT/Apache-2.0"
description = "none for now"

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"

[dev-dependencies]
tempdir = "0.3"