[package]
name = "doxidize"
version = "0.1.0"
authors = ["steveklabnik <steve@steveklabnik.com>"]
license = "MIT/Apache-2.0"
description = "none for now"

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
comrak = "0.2.5"
serde_json = "1.0"
walkdir = "2.0.1"

handlebars = "0.30.0-beta.4" # https://github.com/sunng87/handlebars-rust/issues/194
pest = "=1.0.0-beta.17" # https://github.com/sunng87/handlebars-rust/issues/197

[dev-dependencies]
tempdir = "0.3"
